### ISSUE TITLE
Title and labels etc

### ISSUE THREAD

**Issue by pritpalmarjara** [parvshkhan/TaarAppFinal#2]
1. Please change the name of the app from "TAAR" to "My-travel"
2. Do not use "ctreimg" image - just leave it blank and use text "My-travel" as app name
3. I think the layout for the travel plan that we discussed today is activity_plan.xml.  Please use the activity title as  "New travel request" instead of Travel request form (TAAR).
4. more later...thanks.

**Comment by pritpalmarjara** [comment]
please let me know, by when can I see the changes and progress.

**Comment by parvshkhan** [comment]
> please let me know, by when can I see the changes and progress.

Issue has been resolved .You Can check It .
